#
# Module manifest for module 'PSQueue'
#
# Generated by: Hannes Palmquist
#
# Generated on: 2022-11-14
#

@{
    RootModule           = 'PSQueue.psm1'
    ModuleVersion        = '0.0.1'
    CompatiblePSEditions = @('Desktop', 'Core')
    PowerShellVersion    = '5.1'
    GUID                 = 'ba821fed-a721-459e-825b-1c87090f36ea'
    Author               = 'Hannes Palmquist'
    CompanyName          = 'GetPS'
    Copyright            = '(c) Hannes Palmquist. All rights reserved.'
    Description          = 'Provides tools to work with system.collections.queue arrays'
    RequiredModules      = @()
    FunctionsToExport    = '*'
    CmdletsToExport      = '*'
    VariablesToExport    = '*'
    AliasesToExport      = '*'
    PrivateData          = @{
        PSData = @{
            LicenseUri   = 'https://github.com/hanpq/PSQueue/blob/main/LICENSE'
            # Bug in PowershellGet 3.0.18-beta18 causes packaging of the nuget package to fail when requireLicenseAcceptance is defined.
            #RequireLicenseAcceptance = $false
            Prerelease   = ''
            Tags         = @('PSEdition_Desktop', 'PSEdition_Core', 'Windows', 'Linux', 'MacOS')
            ProjectUri   = 'https://getps.dev/modules/PSQueue/getstarted'
            ReleaseNotes = ''
        }
    }
}
